assessment/urls.py
from django.urls import path, include
from assessment.views import *

app_name = 'assessment'

urlpatterns = [
    path('', assessment_view, name='assessment_view'),
    path('buscar/', search, name='search'),
    path('avaliar/', add_view, name='add_view'),
    path('criar_avaliacao/', add_create, name='add_create'),
    path('<int:id>/', to_view, name='to_view'),
    path('<int:id>/editar', to_edit, name='to_edit'),
    path('<int:id>/editar_avaliacao', edit_create, name='edit_create'),
    path('<int:id>/delete', delete_create, name='delete_create'),
]

enrollment/urls.py
from django.urls import path, include
from enrollment.views import *

app_name = 'enrollment'

urlpatterns = [
    path('', enrollment_view, name='enrollment_view'),
    path('busca/', search, name='search'),
    path('matricular/', add_view, name='add_view'),
    path('criar_matricula/', add_create, name='add_create'),
    path('<int:id>/', to_view, name='to_view'),
    path('<int:id>/editar', to_edit, name='to_edit'),
    path('<int:id>/editar_matricula', edit_create, name='edit_create'),
    path('<int:id>/delete', delete_create, name='delete_create'),
]

gym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('users.urls')),
    path('matriculas/', include('enrollment.urls')),
    path('avaliacoes/', include('assessment.urls')),
    path('', include('home.urls'))
]

assessment/models.py
from django.db import models
from enrollment.models import Registration

# Create your models here.
class Assessment(models.Model):
    choice_is_evaluated = (
        ('True', 'Avaliado'),
        ('False', 'Não Avaliado')
    )

    name   = models.ForeignKey(Registration, on_delete=models.DO_NOTHING)
    height = models.FloatField(null=False)
    weight = models.FloatField(null=False) 
    imc    = models.FloatField(null=False)
    is_evaluated = models.CharField(max_length=5, choices=choice_is_evaluated)

    def __str__(self):
        return f'{self.name}'

enrollment/models.py
from django.db import models
from django.contrib.auth.models import User

class Registration(models.Model):
    choice_ocupation = (
        ('Ex', 'Público Externo'),
        ('E', 'Estudante'), 
        ('F', 'Funcionário')
    )

    choice_is_registered = (
        ('True', 'Matriculado'),
        ('False', 'Não Matriculado')
    )
        
    name          = models.CharField(max_length=100, null=False)
    cpf           = models.CharField(max_length=11, unique=True, null=False)
    sig_register  = models.CharField(max_length=11)
    ocupation     = models.CharField(max_length=2, choices=choice_ocupation, null=False)
    is_registered = models.CharField(max_length=5, choices=choice_is_registered)
    
    def __str__(self):
        return self.name

assessment/forms/assessment_form.py
from django import forms
from utils.django_forms import *
from assessment.models import Assessment
from enrollment.models import Registration
from django.shortcuts import get_object_or_404

class AssessmentForm(forms.ModelForm):
    choice_is_evaluated = (
        ('True', 'Avaliado'),
        ('False', 'Não Avaliado')
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for i, value in self.fields.items():
            add_attr(self.fields[i], 'class', 'form-control')

    class Meta:
        model = Assessment
        fields = [
            'name',
            'height',
            'weight',
            'imc',
            'is_evaluated'
        ]

    name = forms.ModelChoiceField(
        required=True,
        label='Nome:',
        # widget=forms.Select(attrs={'disabled': False}),
        queryset=Registration.objects.all(),
    )

    height = forms.CharField(
        error_messages={'required': 'Digite uma altura.'},
        required=True,
        label='Altura:',
        widget=forms.TextInput(attrs={'disabled': False}),
    )

    weight = forms.CharField(
        required=True,
        label='Peso:',
        error_messages= {'required': 'Esse campo não pode ser vazio.'},
        widget=forms.TextInput(attrs={'disabled': False}),
    )

    imc = forms.CharField(
        required=True,
        error_messages={'required': 'Este Campo é obrigatório.'},
        label='IMC:',
        help_text=(
            'Este campo é calculado de forma automática.'
        ),
        widget=forms.TextInput(attrs={'disabled': False}),
    )

    is_evaluated = forms.ChoiceField(
        required=True,
        widget=forms.Select(attrs={'disabled': False}),
        error_messages={'required': 'Este campo é obrigatório.'},
        label='Status da Avaliação:',
        choices=choice_is_evaluated,
    )

    def clean_height(self):
        height = self.cleaned_data.get('height', '')
        height = height.replace(',', '.')
        try:
            height = float(height)
        except:
            raise forms.ValidationError(
                'A altura precisa ser um número inteiro ou decimal!',
                code='invalid',
            )
        
        return height

    def clean_weight(self):
        weight = self.cleaned_data.get('weight', '')
        weight = weight.replace(',', '.')
        try:
            weight = float(weight)
        except:
            raise forms.ValidationError(
                'O peso precisa ser um número inteiro ou decimal!',
                code='invalid',
            )
        
        return weight

    def clean_name(self):
        name = self.cleaned_data.get('name', '')
        instance = self.instance
        if instance and instance.pk:
            exists = Assessment.objects.exclude(pk=instance.pk).filter(name=name).exists()
        else:
            exists = Assessment.objects.filter(name=name).exists()

        if exists:
            raise forms.ValidationError(
                'Já existe essa avaliação no sistema!',
                code='invalid',
            )
        return name

    def clean(self):
        cleaned_data = super().clean()

assessment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from assessment.models import Assessment
from django.core.paginator import Paginator
from django.db.models import Q
from django.urls import reverse
from django.contrib import messages
from utils.django_forms import add_attr
from .forms import AssessmentForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='users:login', redirect_field_name='next')
def assessment_view(request):
    registers = Assessment.objects.all().order_by('name')

    paginator = Paginator(registers, 8)
    page      = request.GET.get('page')
    objs_per_page = paginator.get_page(page)
    
    return render(request,'assessment/pages/assessment_view.html', {
        'registers': objs_per_page,
        'form_action_search': reverse('assessment:search'),
    })

@login_required(login_url='users:login', redirect_field_name='next')
def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()
    
    registers = Assessment.objects.filter(
        Q(
            Q(name__name__icontains=search_term) # "OR" in database
        ),
    ).order_by('name')

    paginator = Paginator(registers, 8)
    page      = request.GET.get('page')
    objs_per_page = paginator.get_page(page)

    return render(request,'assessment/pages/assessment_view.html', {
        'registers': objs_per_page,
    })

@login_required(login_url='users:login', redirect_field_name='next')
def add_view(request):
    register_form_data = request.session.pop('register_form_data', None)
    form = AssessmentForm(register_form_data)

    return render(
        request, 'assessment/pages/to_view.html', {
            'form': form,
            'title': 'Avaliação',
            'form_action': reverse('assessment:add_create'),
        })

@login_required(login_url='users:login', redirect_field_name='next')
def add_create(request):
    if not request.POST:
        raise Http404()
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = AssessmentForm(POST)

    if form.is_valid():
        assessment = form.save(commit=False)
        assessment.save()

        messages.success(request, 'A avaliação foi salva.')

        del(request.session['register_form_data'])
        return redirect(reverse('assessment:add_view'))
    
    return redirect('assessment:add_view')

@login_required(login_url='users:login', redirect_field_name='next')
def to_view(request, id):
    assessment = Assessment.objects.filter(
        pk=id
    ).order_by('name').first()

    form = AssessmentForm(instance=assessment)

    for field_name, field in form.fields.items():
        field.widget.attrs['disabled']=True
        add_attr(form.fields[field_name], 'class', 'disabled') 

    return render(
        request, 'assessment/pages/to_view.html', {
            'form': form,
            'title': 'Informações da Avaliação',
            'enrollment': assessment
    })

@login_required(login_url='users:login', redirect_field_name='next')
def to_edit(request, id):
    assessment = get_object_or_404(Assessment, pk=id)
    
    register_form_data = request.session.pop('register_form_data', None)
    form = AssessmentForm(register_form_data, instance=assessment)
    
    url_parameter = reverse('assessment:edit_create', kwargs={'id': assessment.id})
    return render(
        request, 'assessment/pages/to_view.html', {
            'form': form,
            'title': 'Atualizar Avaliação',
            'enrollment': assessment,
            'form_action': url_parameter,
    })

@login_required(login_url='users:login', redirect_field_name='next')
def edit_create(request, id):
    if not request.POST:
        raise Http404()
    
    assessment = get_object_or_404(Assessment, pk=id)
    form = AssessmentForm(request.POST, instance=assessment)
    
    url_parameter = reverse('assessment:to_edit', kwargs={'id': assessment.id})
    
    if form.is_valid():
        user = form.save(commit=False)
        user.save()

        messages.success(request, 'A avaliação foi editada.')
        return redirect(url_parameter)
    
    request.session['register_form_data'] = request.POST
    return redirect(url_parameter)

@login_required(login_url='users:login', redirect_field_name='next')
def delete_create(request, id):
    # add here later: request.<is_avaliador, is_admin>
    assessment = get_object_or_404(Assessment, pk=id)
    name = assessment.name
    assessment.delete()

    messages.success(request, f'A avaliação do(a) {name} foi deletada!')
    
    return redirect(reverse('assessment:assessment_view'))

assessment/templates/assessment/pages/add_view.html
{% extends "global/base.html" %}

{% block title %}
    Avaliação
{% endblock title %}

{% block content %}
    {% include "global/partials/form.html" %}
{% endblock content %}

assessment/templates/assessment/pages/assessment_view.html
{% extends "global/base.html" %}

{% block title %}
    Marículas
{% endblock title %}

{% block content %}
    <div class="container mt-2">
        <h2 class="text-center mb-1">Avaliações</h2>
        <div class="form-content form-content-grid my-2" id='message'>
            <div class="form-group">
                {% include "global/partials/message.html" %}
            </div>
        </div>
        <div class="space-search">
            <div class="inline-form">
                {% include "global/partials/search.html" %}
            </div>            
            <div>
                <a class="btn button-1" href="{% url 'assessment:add_view' %}">Adicionar</a>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Status Avaliação</th>
                    <th>Status Matrícula</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for register in registers %}
                    {% include "assessment/partials/modal_delete.html" %}
                    <tr>
                        <td>{{ register.name }}</td>
                        <td>{{ register.get_is_evaluated_display }}</td>
                        <td>{{ register.name.get_is_registered_display }}</td>
                        <td>
                            <a class="btn button-view me-1" href="{% url "assessment:to_view" id=register.pk %}">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                            <a class="btn button-edit me-1" href="{% url "assessment:to_edit" id=register.pk %}">
                                <i class="fa-solid fa-pen"></i>
                            </a>
                            <a class="btn button-delete me-1" data-bs-toggle="modal" data-bs-target="#item-{{register.pk}}">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="...">
            <ul class="pagination">
                {% if registers.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ registers.previous_page_number }}">Anterior</a>
                    </li>
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ registers.previous_page_number }}">{{ registers.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ registers.number }}</a>
                </li>
                
                {% if registers.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ registers.next_page_number }}">{{ registers.next_page_number }}</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ registers.next_page_number }}">Próxima</a></li>
                {% endif %}
            </ul>
          </nav>
    </div>
    <script>
        // Função para excluir o elemento após um certo tempo
        setTimeout(function() {
            var elementoParaExcluir = document.getElementById('message');
            if (elementoParaExcluir) {
                elementoParaExcluir.remove();
            }
        }, 3000); 
    </script>
{% endblock content %}

assessment/templates/assessment/pages/assessments_view.html
{% extends "global/base.html" %}

{% block title %}
    Marículas
{% endblock title %}

{% block content %}
    <div class="container mt-2">
        <h2 class="text-center mb-1">Avaliações</h2>
        <div class="form-content form-content-grid my-2" id='message'>
            <div class="form-group">
                {% include "global/partials/message.html" %}
            </div>
        </div>
        <div class="space-search">
            <div class="inline-form">
                {% include "global/partials/search.html" %}
            </div>            
            <div>
                <a class="btn button-1" href=" {% url 'enrollment:add_view' %}">Adicionar</a>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Status</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for register in registers %}
                    {% include "enrollment/partials/modal_delete.html" %}
                    <tr>
                        <td>{{ register.name }}</td>
                        <td></td>
                        <td>
                            <a class="btn button-view me-1" href="{% url "enrollment:to_view" id=register.pk %}">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                            <a class="btn button-edit me-1" href="{% url "enrollment:to_edit" id=register.pk %}">
                                <i class="fa-solid fa-pen"></i>
                            </a>
                            <a class="btn button-delete me-1" data-bs-toggle="modal" data-bs-target="#item-{{register.pk}}">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="...">
            <ul class="pagination">
                {% if registers.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ registers.previous_page_number }}">Anterior</a>
                    </li>
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="?page={{ registers.previous_page_number }}">{{ registers.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ registers.number }}</a>
                </li>
                
                {% if registers.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ registers.next_page_number }}">{{ registers.next_page_number }}</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ registers.next_page_number }}">Próxima</a></li>
                {% endif %}
            </ul>
          </nav>
    </div>
    <script>
        // Função para excluir o elemento após um certo tempo
        setTimeout(function() {
            var elementoParaExcluir = document.getElementById('message');
            if (elementoParaExcluir) {
                elementoParaExcluir.remove();
            }
        }, 3000); 
    </script>
{% endblock content %}

assessment/templates/assessment/pages/to_view.html
{% extends "global/base.html" %}

{% block title %}
    {{title}}
{% endblock title %}
    {{title}}

{% block content %}
    {% include "global/partials/form.html" %}
{% endblock content %}